server:
  port: 9005
logging:
  pattern:
    console: '%d{HH:mm:ss.SSS} %clr(%-5p) [%10.10t] %-30.40logger{0} %m%n'
  level:
    org.springframework: warn
spring:
  main.banner-mode: 'off'

service.create:
    min-wait: 1
    max-wait: 10