camunda.url: http://localhost:8080/engine-rest
server:
  port: 9003
topic:
    create-inventory: create-generic-vport
    fail-inventory-vport: fail-inventory-vport
    generic-vport-created: generic-vport-created
logging:
  pattern:
    console: '%d{HH:mm:ss.SSS} %clr(%-5p) [%10.10t] %-30.40logger{0} %m%n'
  level:
    org.springframework: warn
spring:
  application.name: inventory-worker
  main.banner-mode: 'off'