server:
  port: 9001
camunda.url: http://localhost:8080
db-worker.url: http://localhost:9002
logging:
  pattern:
    console: '%d{HH:mm:ss.SSS} %clr(%-5p) [%10.10t] %-30.40logger{0} %m%n'
  level:
    org.springframework: warn
spring:
  main.banner-mode: 'off'