camunda.url: http://localhost:8080/engine-rest
server:
  port: 9002

topic:
    create-db-vport: create-db-vport
    fail-db-vport: fail-db-vport
    db-vport-created: db-vport-created
logging:
  pattern:
    console: '%d{HH:mm:ss.SSS} %clr(%-5p) [%10.10t] %-30.40logger{0} %m%n'
  level:
    org.springframework: warn
spring:
  application.name: db-worker
  main.banner-mode: 'off'